### ISSUE TITLE
Is the hardware address correct?

### ISSUE THREAD

**Issue by NNGB-kor** [RobTillaart/MCP23S17#36]
check the datasheet of the 'microchip' company, the hardware address will be as shown in the image.
![2024-02-24 233625](https://github.com/RobTillaart/MCP23S17/assets/96456418/e34110ca-9375-4164-86e1-a1827e154904)

The hardware address is 0x00 0x01... Is this correct?
0x20 0x21 0x22... is correct?

**Comment by RobTillaart** [comment]
Thanks for the question.
Will investigate coming week

**Comment by RobTillaart** [comment]
@NNGB-kor 

Had a quick look as the library just works.


The 0x2.. is handled low level in MCP23S17.cpp around line 590 by the two masks.
the 0x4_ part is the shifted 0x2_ part of the address. 

```cpp
////////////////////////////////////////////////////
//
//  PRIVATE
//

//  low level read / write masks
#define MCP23S17_WRITE_REG    0x40
#define MCP23S17_READ_REG     0x41
```

- https://github.com/RobTillaart/MCP23S17/blob/master/MCP23S17.cpp#L594

Does this solve your question?

**Comment by RobTillaart** [comment]
Assuming this solved the problem, I close this issue.
Feel free to reopen if needed.
